name: Java CI

on: [ push ]

jobs:
  build:

    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 1.8
        uses: actions/setup-java@main
        with:
          java-version: '8.0.292+10'
          distribution: 'adopt'

      - uses: actions/cache@main
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Gradle
        run: gradle build

      - uses: actions/upload-artifact@main
        with:
          name: Chatty
          path: build/libs/Chatty.jar
