name: Java CI

on: [ push ]

jobs:
  build:

    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Java 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - uses: actions/cache@main
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Gradle
        run: gradle build

      - uses: actions/upload-artifact@main
        with:
          name: Chatty
          path: build/libs/*.jar
